# Generated by Django 2.1.5 on 2022-07-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('walmart_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('broulims_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('albertsons_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
