# Generated by Django 2.1.5 on 2022-07-19 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_auto_20220719_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 14, 50, 59, 72279, tzinfo=utc)),
        ),
    ]
