# Generated by Django 2.1.5 on 2022-07-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walmart_list', models.TextField(max_length=10000, null=True)),
                ('broulims_list', models.TextField(max_length=10000, null=True)),
                ('albertsons_list', models.TextField(max_length=10000, null=True)),
            ],
        ),
    ]
