# Generated by Django 2.1.5 on 2022-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='albertsons_list',
        ),
        migrations.RemoveField(
            model_name='list',
            name='broulims_list',
        ),
        migrations.RemoveField(
            model_name='list',
            name='walmart_list',
        ),
        migrations.AddField(
            model_name='list',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='store',
            field=models.CharField(default='walmart', max_length=50),
            preserve_default=False,
        ),
    ]
